### ISSUE TITLE
configuration is not valid

### ISSUE THREAD

**Issue by enygmait** [chomupashchuk/ariston-remotethermo-home-assistant-v2#44]
hello friend after many months of use without any problem for a few days integration does not work I have the following error:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:693
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:16:42 (2 occurrences)
Last logged: 11:20:55

[547678460688] The system cannot restart because the configuration is not valid: Invalid config for [ariston]: value must be one of ['ch_antifreeze_temperature', 'ch_comfort_temperature', 'ch_detected_temperature', 'ch_economy_temperature', 'ch_electricity_last_month', 'ch_energy2_last_7_days', 'ch_energy2_last_month', 'ch_energy2_last_year', 'ch_energy2_this_month', 'ch_energy2_this_year', 'ch_energy2_today', 'ch_energy2_yesterday', 'ch_energy_last_7_days', 'ch_energy_last_month', 'ch_energy_last_year', 'ch_energy_this_month', 'ch_energy_this_year', 'ch_energy_today', 'ch_energy_yesterday', 'ch_fixed_temperature', 'ch_flow_temperature', 'ch_gas_last_month', 'ch_mode', 'ch_program', 'ch_set_temperature', 'ch_water_temperature', 'dhw_comfort_function', 'dhw_comfort_temperature', 'dhw_economy_temperature', 'dhw_electricity_last_month', 'dhw_energy2_last_7_days', 'dhw_energy2_last_month', 'dhw_energy2_last_year', 'dhw_energy2_this_month', 'dhw_energy2_this_year', 'dhw_energy2_today', 'dhw_energy2_yesterday', 'dhw_energy_last_7_days', 'dhw_energy_last_month', 'dhw_energy_last_year', 'dhw_energy_this_month', 'dhw_energy_this_year', 'dhw_energy_today', 'dhw_energy_yesterday', 'dhw_gas_last_month', 'dhw_mode', 'dhw_program', 'dhw_set_temperature', 'dhw_storage_temperature', 'dhw_thermal_cleanse_cycle', 'errors_count', 'integration_version', 'mode', 'outside_temperature', 'pressure', 'signal_strength', 'units'] @ data['ariston'][0]['sensors'][0]. Got None value must be one of ['ch_antifreeze_temperature', 'ch_comfort_temperature', 'ch_detected_temperature', 'ch_economy_temperature', 'ch_electricity_last_month', 'ch_energy2_last_7_days', 'ch_energy2_last_month', 'ch_energy2_last_year', 'ch_energy2_this_month', 'ch_energy2_this_year', 'ch_energy2_today', 'ch_energy2_yesterday', 'ch_energy_last_7_days', 'ch_energy_last_month', 'ch_energy_last_year', 'ch_energy_this_month', 'ch_energy_this_year', 'ch_energy_today', 'ch_energy_yesterday', 'ch_fixed_temperature', 'ch_flow_temperature', 'ch_gas_last_month', 'ch_mode', 'ch_program', 'ch_set_temperature', 'ch_water_temperature', 'dhw_comfort_function', 'dhw_comfort_temperature', 'dhw_economy_temperature', 'dhw_electricity_last_month', 'dhw_energy2_last_7_days', 'dhw_energy2_last_month', 'dhw_energy2_last_year', 'dhw_energy2_this_month', 'dhw_energy2_this_year', 'dhw_energy2_today', 'dhw_energy2_yesterday', 'dhw_energy_last_7_days', 'dhw_energy_last_month', 'dhw_energy_last_year', 'dhw_energy_this_month', 'dhw_energy_this_year', 'dhw_energy_today', 'dhw_energy_yesterday', 'dhw_gas_last_month', 'dhw_mode', 'dhw_program', 'dhw_set_temperature', 'dhw_storage_temperature', 'dhw_thermal_cleanse_cycle', 'errors_count', 'integration_version', 'mode', 'outside_temperature', 'pressure', 'signal_strength', 'units'] @ data['ariston'][0]['sensors'][10]. Got None. (See /config/configuration.yaml, line 13).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 693, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [ariston]: value must be one of ['ch_antifreeze_temperature', 'ch_comfort_temperature', 'ch_detected_temperature', 'ch_economy_temperature', 'ch_electricity_last_month', 'ch_energy2_last_7_days', 'ch_energy2_last_month', 'ch_energy2_last_year', 'ch_energy2_this_month', 'ch_energy2_this_year', 'ch_energy2_today', 'ch_energy2_yesterday', 'ch_energy_last_7_days', 'ch_energy_last_month', 'ch_energy_last_year', 'ch_energy_this_month', 'ch_energy_this_year', 'ch_energy_today', 'ch_energy_yesterday', 'ch_fixed_temperature', 'ch_flow_temperature', 'ch_gas_last_month', 'ch_mode', 'ch_program', 'ch_set_temperature', 'ch_water_temperature', 'dhw_comfort_function', 'dhw_comfort_temperature', 'dhw_economy_temperature', 'dhw_electricity_last_month', 'dhw_energy2_last_7_days', 'dhw_energy2_last_month', 'dhw_energy2_last_year', 'dhw_energy2_this_month', 'dhw_energy2_this_year', 'dhw_energy2_today', 'dhw_energy2_yesterday', 'dhw_energy_last_7_days', 'dhw_energy_last_month', 'dhw_energy_last_year', 'dhw_energy_this_month', 'dhw_energy_this_year', 'dhw_energy_today', 'dhw_energy_yesterday', 'dhw_gas_last_month', 'dhw_mode', 'dhw_program', 'dhw_set_temperature', 'dhw_storage_temperature', 'dhw_thermal_cleanse_cycle', 'errors_count', 'integration_version', 'mode', 'outside_temperature', 'pressure', 'signal_strength', 'units'] @ data['ariston'][0]['sensors'][0]. Got None
value must be one of ['ch_antifreeze_temperature', 'ch_comfort_temperature', 'ch_detected_temperature', 'ch_economy_temperature', 'ch_electricity_last_month', 'ch_energy2_last_7_days', 'ch_energy2_last_month', 'ch_energy2_last_year', 'ch_energy2_this_month', 'ch_energy2_this_year', 'ch_energy2_today', 'ch_energy2_yesterday', 'ch_energy_last_7_days', 'ch_energy_last_month', 'ch_energy_last_year', 'ch_energy_this_month', 'ch_energy_this_year', 'ch_energy_today', 'ch_energy_yesterday', 'ch_fixed_temperature', 'ch_flow_temperature', 'ch_gas_last_month', 'ch_mode', 'ch_program', 'ch_set_temperature', 'ch_water_temperature', 'dhw_comfort_function', 'dhw_comfort_temperature', 'dhw_economy_temperature', 'dhw_electricity_last_month', 'dhw_energy2_last_7_days', 'dhw_energy2_last_month', 'dhw_energy2_last_year', 'dhw_energy2_this_month', 'dhw_energy2_this_year', 'dhw_energy2_today', 'dhw_energy2_yesterday', 'dhw_energy_last_7_days', 'dhw_energy_last_month', 'dhw_energy_last_year', 'dhw_energy_this_month', 'dhw_energy_this_year', 'dhw_energy_today', 'dhw_energy_yesterday', 'dhw_gas_last_month', 'dhw_mode', 'dhw_program', 'dhw_set_temperature', 'dhw_storage_temperature', 'dhw_thermal_cleanse_cycle', 'errors_count', 'integration_version', 'mode', 'outside_temperature', 'pressure', 'signal_strength', 'units'] @ data['ariston'][0]['sensors'][10]. Got None. (See /config/configuration.yaml, line 13). 

thanks for help

**Comment by chomupashchuk** [comment]
Ariston changed API and I had to rework the integration, many parameters have changed in the proccess (some removed, some renamed, some replaced).
See README.md file for supported parameters and change data in configuration.yaml
