### ISSUE TITLE
Problems on new HA?

### ISSUE THREAD

**Issue by inode-** [chomupashchuk/ariston-remotethermo-home-assistant-v2#52]
On HA 2022.11.2:

```
2022-11-14 13:21:07.041 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.ariston
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/ariston/__init__.py", line 25, in <module>
    from .ariston import AristonHandler
  File "/home/pi/.homeassistant/custom_components/ariston/ariston.py", line 12, in <module>
    class AristonHandler:
  File "/home/pi/.homeassistant/custom_components/ariston/ariston.py", line 402, in AristonHandler
    append_param(sensor, _MAP_ARISTON_MULTIZONE_PARAMS, _SENSOR_SET_LIST)
TypeError: 'staticmethod' object is not callable
```

It's only on me?

**Comment by paluszak** [comment]
The same here.
