### ISSUE TITLE
Not possible to connect

### ISSUE THREAD

**Issue by lmcluis** [chomupashchuk/ariston-remotethermo-home-assistant-v2#58]
When I'm trying to setup this integration I get this error.
Note: this integration was working well until now.
"Cannot connect to host www.ariston-net.remotethermo.com:443"

Log trace:
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ariston/ariston_api.py", line 390, in async_connect
    response = await self._async_post(
  File "/usr/local/lib/python3.10/site-packages/ariston/ariston_api.py", line 711, in _async_post
    return await self.__async_request("POST", path, None, body)
  File "/usr/local/lib/python3.10/site-packages/ariston/ariston_api.py", line 685, in __async_request
    response = await session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.ariston-net.remotethermo.com:443 ssl:default [Try again]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ariston/config_flow.py", line 68, in async_step_user
    reponse = await ariston.async_connect(
  File "/usr/local/lib/python3.10/site-packages/ariston/__init__.py", line 46, in async_connect
    return await self.api.async_connect()
  File "/usr/local/lib/python3.10/site-packages/ariston/ariston_api.py", line 403, in async_connect
    raise ConnectionException() from error
ariston.ariston_api.ConnectionException

**Comment by lmcluis** [comment]
This is not an issue with this integration
