### ISSUE TITLE
Ariston Alteas one error

### ISSUE THREAD

**Issue by jello1974** [chomupashchuk/ariston-remotethermo-home-assistant-v2#7]
Hello,

Today a gas regulator failed and the heater stoped working with no flame error.
At the same moment home assistant raised an error 
2020-12-08 08:20:36 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ariston_active_errors fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/ariston/sensor.py", line 271, in update
    self._attrs[valid_error] = ""
TypeError: unhashable type: 'dict'

**Comment by chomupashchuk** [comment]
Error parsing is related to ticket https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/issues/6
It was fixed and is available for the download

**Comment by jello1974** [comment]
Thank you,
Tested and working like a charm.
